### ISSUE TITLE
Cant access settings

### ISSUE THREAD

**Issue by Zorro122** [PhilippC/keepass2android#196]
When I am logged in to my database and I want to open the settings I get directly logged out and see again the login screen.

**Comment by Zorro122** [comment]
P.S. Version 1.04-pre2 on Android 7.1.1 (Oneplus 5T)

**Comment by suiang** [comment]
Me too，Meizu Pro6 Plus Android ：7.0.0

**Comment by iceman73** [comment]
Another user with the settings issue running Android 7.0.0 on a LG g6

**Comment by moritz1000** [comment]
When I log into my database and open the settings inside the keepass2android app, the app crashes.

**Comment by PhilippC** [comment]
I could not reproduce this but saw the crash reports on Google Play. should be fixed with 1.04-pre3 which is now in beta channel. Can you please test if it's working again?

**Comment by moritz1000** [comment]
I just testet it, it's still not working. I will send another bug report...
But thank you for your work!

PhilippC <notifications@github.com> schrieb am Mo., 8. Jan. 2018, 11:30:

**Comment by moritz1000** [comment]
I tested it with another keepass database from Google Drive and I get the
same problem. When I opt out of the beta and use the stable version it's
working.

Moritz John <moritz1000@gmail.com> schrieb am Mo., 8. Jan. 2018, 11:39:

**Comment by moritz1000** [comment]
When will be 1.04-pre3 live? I will test it as soon as I get the update.

**Comment by iceman73** [comment]
Just waiting for 1.04-pr3 to be available

**Comment by uwekoegel** [comment]
I have the same issue.
Using Oppo F1f with Android 5.1.1

With Version 1.04 I don't had that issue.
After updating to Version 1.04-pre2 I have that issue.

I have get a error message that said something about "onedrive sdk"

**Comment by Sanaki** [comment]
@PhilippC I'm not sure what's up, but I still don't see 1.04-pre3 in beta six days later. It's still showing 1.04-pre2.

**Comment by PhilippC** [comment]
can anybody collect a logcat? I don't see any report of this on Google Play, nor can I reproduce this on any of my devices.

**Comment by suiang** [comment]
Not getting any updates about 1.04-pre3


来自 魅族 PRO 6 Plus

-------- 原始邮件 --------
发件人：PhilippC <notifications@github.com>
时间：周一 1月15日 17:11
收件人：PhilippC/keepass2android <keepass2android@noreply.github.com>
抄送：苏扬 <xitem@163.com>,Comment <comment@noreply.github.com>
主题：Re: [PhilippC/keepass2android] Cant access settings (#196)

**Comment by moritz1000** [comment]
How can I privatley send you a logcat? I used Logcat [NO ROOT] via ADB.

**Comment by PhilippC** [comment]
please send it crocoapps@gmail.com. I even set up an emulator running Android 7 but everything's working there...

**Comment by moritz1000** [comment]
Yeah I did not get an update to 1.04-pre3 in the last week. I will tell you if it is fixed as soon as the update is available to me.

**Comment by suiang** [comment]
It's updated, and it's running now｡◕‿◕｡


来自 魅族 PRO 6 Plus

**Comment by iceman73** [comment]
Confirmed fix here as well

**Comment by Zorro122** [comment]
I can confirm it too, I'll close the issue. Thank you very much for the fix.
