### ISSUE TITLE
[FEAT] "source file and cache are synchronized" in the way of the keyboard in app

### ISSUE THREAD

**Issue by Account99999** [PhilippC/keepass2android#2626]
Upon opening the app, the notification "source file and cache are synchronized" pops up and partially blocks the keyboard, and every single time I must wait until it disappears so that I can input my password. Very annoying!
![Screenshot_20240625-210109](https://github.com/PhilippC/keepass2android/assets/173972229/b294cf28-39bc-4119-850a-6eb1d916d9ed)

**Comment by MrFishFinger** [comment]
I also find this very frustrating. Is there perhaps a way to disable this, or work around it somehow?

**Comment by frech-tech** [comment]
I have the same problem. I always have to wait for the pop-up to go away.

**Comment by Krzysi3k** [comment]
I agree this is the most annoying thing of the app.

**Comment by PhilippC** [comment]
it is fixed in https://github.com/PhilippC/keepass2android/pull/2826

**Comment by Account99999** [comment]
It is very much not fixed I'm afraid. App updated, I just checked.

**Comment by Account99999** [comment]
App appears updated per Google Play Store, problem still persists:

![Image](https://github.com/user-attachments/assets/b8e750be-d3c9-4fd4-b9c9-e103e0d39bab)

**Comment by PhilippC** [comment]
this is not https://github.com/PhilippC/keepass2android/releases/tag/v1.12-r4

**Comment by Account99999** [comment]
I see the old version is on Google Play store. When will the latest updated version be available? I can only open the app there, no option to update it yet.

**Comment by PhilippC** [comment]
you can install from https://github.com/PhilippC/keepass2android/releases or join beta (https://play.google.com/apps/testing/keepass2android.keepass2android) to get it now. This version has an issue with Yubikey and might crash if you use a very old OneDrive provider. I need to fix these things before I can publish fully and don't know when that will be.
