### ISSUE TITLE
[BUG] White screen flashes on cold launch

### ISSUE THREAD

**Issue by nicdnb** [PhilippC/keepass2android#2757]
### Checks

- [x] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Thanks for a great app! Has been my go to for a while now...

One thing that I wish we could improve is that even though my device is on dark mode, whenever I cold start the app there is a bright white screen before the app launches...

Thanks!

### Describe what you expected to happen:

Perhaps on app launch we can have a dark splash screen or a splash screen that matches the device theme?

### What version of Keepass2Android are you using?

1.09e-r7

### Which version of Android are you on?

15

**Comment by Spiralpine** [comment]
+1

**Comment by Gian-Fr** [comment]
This should have been solved with the latest version. When i open the app using dark mode the splash screen is also dark
 suggest to close this @PhilippC

**Comment by PhilippC** [comment]
I still see the white splashscreen. I guess this is because the app doesn't have anything defined regarding the splash screen. Should be doable by integrating https://developer.android.com/jetpack/androidx/releases/core#core_splashscreen_version_12_2  or so
