### ISSUE TITLE
Biometric Unlock

### ISSUE THREAD

**Issue by DPac55** [PhilippC/keepass2android#3013]
### Checks

- [x] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Biometric Unlock is not working properly, I am constantly having to enter my main password or the quick unlock and even that isn't consistent. And every time I go into the settings and enable Full Biometric Unlock but still will not work.

### What version of Keepass2Android are you using?

1.12-r5

### Which version of Android are you on?

15

**Comment by imran** [comment]
Experiencing the same bug 

V 1.12-r5
Android 16

**Comment by guto214** [comment]
I'm encountering the same issue. Can't no longer use "Biometric Unlock" since approximately September 1st.
Android 15
KPass2And version 1.12-r5

**Comment by PhilippC** [comment]
Please join the beta channel (https://play.google.com/apps/testing/keepass2android.keepass2android) and verify that this is fixed there.

**Comment by guto214** [comment]
Thanks for the hint Philipp.
Have updated to the beta version, but still have the same behavior.

Have completely uninstalled, then re-installed K2A: Biometric use is still
not possible.

Anyway, thanks again.

Gustav.

**Comment by PhilippC** [comment]
which version did you test with exactly? (See settings - about)

**Comment by guto214** [comment]
> which version did you test with exactly? (See settings - about)

Issue has initially occurred with ver. "1.12-r5".

**Comment by IzzyHarrell** [comment]
I have the same issue for a few weeks now.
But it happens only occasionally.
Sometimes, when I open keepass and see the login screen, I need to type the password and biometric is not available anymore. When it happens a short error message appears at the bottom of the screen. But it disappears in less then a second, so that I cannot read it. Maybe it is something like "biometric revoked" or similar. But I can be completely wrong and recall it not correctly.
After I logged in with my password, I am asked if I want to activate biometrics. When I activate it, biometric works for a couple of weeks until it fails again. 
I am using Google Pixel 8, Android 16. 

Sorry for the vague info, but maybe it helps. Thanks for your cool tool, Philipp. I am using it for years. 

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/9114e3e2-362d-4b28-bd22-2209843503f8" />

**Comment by imran** [comment]
This appears fixed in the recent beta, Android 16, thank you

**Comment by DeeScully** [comment]
This started happening for me recently. On v1. 14-r0 with Android v13

Tried to use the non-bio quick unlock and it behaves the same. Somehow, the db seems to be closing? When I try to click the icon to open keepass, it'll load the splash, then nothing happens, and if i try the icon again, it'll load the login where I have to input my full master pw.

Is there an easy way for me to roll back to v1. 13?

I think something similar happened around the same time a few years ago? Not sure if it has to do with the oktober notifications or if it's just coincidence.

**Comment by PhilippC** [comment]
@DeeScully to roll back, I'd uninstall the app and download an older version from https://github.com/PhilippC/keepass2android/releases. I have no idea why this should help (but also none why the issue appears).

**Comment by DeeScully** [comment]
> [@DeeScully](https://github.com/DeeScully) to roll back, I'd uninstall the app and download an older version from https://github.com/PhilippC/keepass2android/releases. I have no idea why this should help (but also none why the issue appears).

@PhilippC I followed your instructions. Uninstalled my 1.14-r0 and d/l and installed your 1.13-r0 apk for arm64. And, it seems to be working as expected now. Whatever changes you made between 1.13-r0 and 1.14-r0 may be causing this issue of the db somehow constantly closing and needing the master p/w to reopen.

**Comment by DeeScully** [comment]
@DPac55 were you able to get yours working too?

**Comment by DPac55** [comment]
Yes, with the new update it has been working fine

New version 1.14-r0

**Comment by MattW2** [comment]
Confirmed working after clear storage. 
Clear cache alone did not work
keepass2android version : 1.15-pre0
Android 16
Pixel 10 Pro

@PhilippC, thank you for the fantastic app!!
