### ISSUE TITLE
[BUG] [WebDAV] Java.Lang.IllegalArgumentException: Unexpected char

### ISSUE THREAD

**Issue by freezewind** [PhilippC/keepass2android#3030]
### Checks

- [x] I have read the FAQ section, searched the open issues, and still think this is a new bug.

### Describe the bug you encountered:

Keepass2android shows error during sync database with WebDAV path, and then the target db_name.kdbx doesn't synchronize with the DB and  create db_name.kdbx.tmp.XXXXXXXX (X is 8 digits int) in the same folder at WebDAV path.
After checking the log, it is en IllegalArgumentException from okhttp3 that caused by invalid data in header.
(Ref: https://stackoverflow.com/questions/56323203/okhttp3-java-lang-illegalargumentexception-unexpected-char-0x2019)

### Describe what you expected to happen:

Keepass2android should synchronize database without error and creating tem file.

### What version of Keepass2Android are you using?

v1.14-r1

### Which version of Android are you on?

Android 15

<Details markdown="block">
<summary>Log</summary>

```plaintext
2025/09/26 19:25:24:474 -- Unexpected char 0x4e00 at 41 in Destination value: https://example.local:34567/db.kdbx
2025/09/26 19:25:24:477 -- System.Exception: Unexpected char 0x4e00 at 41 in Destination value: https://example.local:34567/db.kdbx ---> 
Java.Lang.IllegalArgumentException: Unexpected char 0x4e00 at 41 in Destination value: https://example.local:34567/db.kdbx
	at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
	at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
	at Keepass2android.Javafilestorage.WebDavStorage.UploadFile(String path, Byte[] data, Boolean writeTransactional)
	at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
--- End of managed Java.Lang.IllegalArgumentException stack trace

---java.lang.IllegalArgumentException: Unexpected char 0x4e00 at 41 in Destination value: https://example.local:34567/db.kdbx
	at okhttp3.Headers$Companion.checkValue(Headers.kt:450) 
	at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362) 
	at okhttp3.Headers$Builder.set(Headers.kt:344) 
	at okhttp3.Request$Builder.header(Request.kt:199) 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:228) 
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:282) 
	at mono.java.lang.RunnableImplementor.n_run(Native Method) 
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29) 
	at java.lang.Thread.run(Thread.java:1012)  
--- End of managed Java.Lang.IllegalArgumentException stack trace

---java.lang.IllegalArgumentException: Unexpected char 0x4e00 at 41 in Destination value: https://example.local:34567/db.kdbx
	at okhttp3.Headers$Companion.checkValue(Headers.kt:450) at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
	at okhttp3.Headers$Builder.set(Headers.kt:344) at okhttp3.Request$Builder.header(Request.kt:199)
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:228)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:282)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1012)
Exception_EndOfInnerExceptionStack
	at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
	at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
	at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(IOConnectionInfo ioc, Boolean useFileTransaction)
	at keepass2android.SynchronizeCachedDatabase.Run()
```

</Details>

**Comment by giopas** [comment]
I confirm what seems to me the same or quite related issue.

I particular the issue is the following:

Rename/Move failed
couldn't save to remote

Java.Lang.Exception: Rename/Move failed for [..] to [..]:502

Here is the tracelog:

```
9/26/2025 10:47:53 PM:600 -- DatabaseSettingsActivity.OnPause 50
9/26/2025 10:47:53 PM:600 -- Timeout start
9/26/2025 10:47:55 PM:494 -- DatabaseSettingsActivity.OnResume 50
9/26/2025 10:47:55 PM:496 --  DatabaseIsUnlocked=True 50
9/26/2025 10:47:55 PM:497 -- Timeout cancel
9/26/2025 10:47:58 PM:178 -- DatabaseSettingsActivity.OnPause 50
9/26/2025 10:47:58 PM:180 -- Timeout start
9/26/2025 10:47:58 PM:199 -- GroupActivity.OnStart 49
9/26/2025 10:47:58 PM:200 -- GroupActivity.OnResume 49
9/26/2025 10:47:58 PM:200 --  DatabaseIsUnlocked=True 49
9/26/2025 10:47:58 PM:201 -- Timeout cancel
9/26/2025 10:47:58 PM:755 -- DatabaseSettingsActivity.OnStop 50
9/26/2025 10:47:58 PM:759 -- DatabaseSettingsActivity.OnDestroyTrue 50
9/26/2025 10:47:59 PM:729 -- QuickLocking database
9/26/2025 10:47:59 PM:743 -- Starting/Updating OngoingNotificationsService. Database QuickLocked
9/26/2025 10:47:59 PM:752 -- Finishing crc64c98c008c0cd742cb.GroupActivity due to database lock
9/26/2025 10:47:59 PM:754 -- GroupActivity.OnPause 49
9/26/2025 10:47:59 PM:762 -- SelectCurrentDbActivity.OnStart 47
9/26/2025 10:47:59 PM:764 -- SelectCurrentDbActivity 47: OnActivityResult FirstUser/0
9/26/2025 10:47:59 PM:764 -- TryGetFromActivityResult: no data
9/26/2025 10:47:59 PM:766 -- Task in activity SelectCurrentDbActivity 47 changed to NullTask
9/26/2025 10:47:59 PM:766 -- Finishing SelectCurrentDbActivity 47
9/26/2025 10:47:59 PM:770 -- Finishing SelectCurrentDbActivity 47
9/26/2025 10:48:00 PM:866 -- GroupActivity.OnStop 49
9/26/2025 10:48:00 PM:868 -- GroupActivity.OnDestroyTrue 49
9/26/2025 10:48:00 PM:921 -- SelectCurrentDbActivity.OnStop 47
9/26/2025 10:48:00 PM:922 -- SelectCurrentDbActivity.OnDestroyTrue 47
9/26/2025 10:48:02 PM:849 -- OngoingNotificationsService.OnTaskRemoved: android.intent.action.MAIN
9/26/2025 10:48:02 PM:850 -- Database already QuickLocked
9/26/2025 10:48:02 PM:856 -- Starting/Updating OngoingNotificationsService. Database QuickLocked
9/26/2025 10:48:04 PM:188 -- KeePass.OnCreate 51
9/26/2025 10:48:04 PM:189 -- KeePass:apptask= 51
9/26/2025 10:48:04 PM:189 -- Loaded task keepass2android.NullTask
9/26/2025 10:48:04 PM:189 -- Task in activity KeePass 51 changed to NullTask
9/26/2025 10:48:04 PM:189 -- KeePass.OnCreate
9/26/2025 10:48:04 PM:191 -- KeePass.OnStart 51
9/26/2025 10:48:04 PM:191 -- KeePass.OnStart
9/26/2025 10:48:04 PM:216 -- SelectCurrentDbActivity.OnCreate 52
9/26/2025 10:48:04 PM:217 -- SelectCurrentDbActivity:apptask= 52
9/26/2025 10:48:04 PM:220 -- Loaded task keepass2android.NullTask
9/26/2025 10:48:04 PM:220 -- Task in activity SelectCurrentDbActivity 52 changed to NullTask
9/26/2025 10:48:04 PM:221 -- SelectCurrentDbActivity.OnStart 52
9/26/2025 10:48:04 PM:222 -- SelectCurrentDbActivity.OnResume 52
9/26/2025 10:48:04 PM:222 -- DatabaseIsUnlocked=False 52
9/26/2025 10:48:04 PM:222 -- Starting QuickUnlock
9/26/2025 10:48:04 PM:228 -- SelectCurrentDbActivity.OnPause 52
9/26/2025 10:48:04 PM:237 -- QuickUnlock.OnCreate 53
9/26/2025 10:48:04 PM:237 -- QuickUnlock:apptask= 53
9/26/2025 10:48:04 PM:237 -- Secure display disabled by user preference.
9/26/2025 10:48:04 PM:252 -- QuickUnlock.OnStart 53
9/26/2025 10:48:04 PM:253 -- QuickUnlock.OnResume 53
9/26/2025 10:48:04 PM:253 --  DatabaseIsUnlocked=False 53
9/26/2025 10:48:04 PM:253 -- InitFingerprintUnlock
9/26/2025 10:48:04 PM:254 -- BiometricHardware available = 0
9/26/2025 10:48:04 PM:254 -- fpModule.IsHardwareAvailable=True
9/26/2025 10:48:04 PM:255 -- BiometricHardware available = 0
9/26/2025 10:48:04 PM:255 -- FP: Create BiometricDecryption
9/26/2025 10:48:04 PM:256 -- FP: Init for Dec
9/26/2025 10:48:04 PM:257 -- alias: keepass2android.kp2a_ioc_8088877B910E0076004D23A86FDB169CD51BB81A73DE13F02C47D2540247D113
9/26/2025 10:48:04 PM:257 -- KS: end aliases
9/26/2025 10:48:04 PM:263 -- successfully initialized fingerprint.
9/26/2025 10:48:04 PM:263 -- Fingerprint: StartListening 
9/26/2025 10:48:04 PM:733 -- KeePass.OnStop 51
9/26/2025 10:48:04 PM:736 -- KeePass.OnDestroyTrue
9/26/2025 10:48:04 PM:737 -- KeePass.OnDestroyTrue 51
9/26/2025 10:48:04 PM:752 -- SelectCurrentDbActivity.OnStop 52
9/26/2025 10:48:05 PM:634 -- OnFingerprintAuthSucceeded
9/26/2025 10:48:05 PM:635 -- Fingerprint: StopListening  having prompt 
9/26/2025 10:48:05 PM:707 -- parsing autofillStructure...
9/26/2025 10:48:05 PM:707 -- Parsing done
9/26/2025 10:48:05 PM:708 -- cannot autofill
9/26/2025 10:48:06 PM:141 -- Timeout cancel
9/26/2025 10:48:06 PM:157 -- Starting/Updating OngoingNotificationsService. Database Unlocked
9/26/2025 10:48:06 PM:180 -- FP: Stop listening
9/26/2025 10:48:06 PM:180 -- Fingerprint: StopListening  having prompt 
9/26/2025 10:48:06 PM:182 -- QuickUnlock.OnPause 53
9/26/2025 10:48:06 PM:190 -- SelectCurrentDbActivity.OnStart 52
9/26/2025 10:48:06 PM:192 -- SelectCurrentDbActivity 52: OnActivityResult Canceled/0
9/26/2025 10:48:06 PM:192 -- TryGetFromActivityResult: no data
9/26/2025 10:48:06 PM:193 -- SelectCurrentDbActivity.OnResume 52
9/26/2025 10:48:06 PM:193 --  DatabaseIsUnlocked=True 52
9/26/2025 10:48:06 PM:206 -- SelectCurrentDbActivity.OnPause 52
9/26/2025 10:48:06 PM:218 -- GroupActivity.OnCreate 54
9/26/2025 10:48:06 PM:218 -- GroupActivity:apptask= 54
9/26/2025 10:48:06 PM:218 -- Secure display disabled by user preference.
9/26/2025 10:48:06 PM:219 -- Loaded task keepass2android.NullTask
9/26/2025 10:48:06 PM:219 -- Task in activity GroupActivity 54 changed to NullTask
9/26/2025 10:48:06 PM:236 -- GroupActivity.OnStart 54
9/26/2025 10:48:06 PM:236 -- GroupActivity.OnResume 54
9/26/2025 10:48:06 PM:236 -- DatabaseIsUnlocked=True 54
9/26/2025 10:48:06 PM:237 -- Timeout cancel
9/26/2025 10:48:06 PM:768 -- QuickUnlock.OnStop 53
9/26/2025 10:48:06 PM:769 -- QuickUnlock.OnDestroyTrue 53
9/26/2025 10:48:06 PM:775 -- SelectCurrentDbActivity.OnStop 52
9/26/2025 10:48:10 PM:341 -- status message: Initializing...
9/26/2025 10:48:10 PM:342 -- status submessage: 
9/26/2025 10:48:10 PM:363 -- status message: Synchronizing cached database…
9/26/2025 10:48:10 PM:364 -- status submessage: Loading source file…
9/26/2025 10:48:10 PM:944 -- Checking for file change. Current hash = 3D4B4429F103E09F5310600AEF5D73816CA78CF661836224543B9AE1E61511A3
9/26/2025 10:48:10 PM:945 --[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx) baseVersionHash = 756BC2860AF719D8DB3F441E42FC59D2F3F88F699DD0021AD49D71256D930889
9/26/2025 10:48:10 PM:946 -- Checking for file change. baseVersionHash = 756BC2860AF719D8DB3F441E42FC59D2F3F88F699DD0021AD49D71256D930889
9/26/2025 10:48:10 PM:947 --[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx) isCached = True
9/26/2025 10:48:10 PM:947 --[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx) localVersionHash = E2D46B90EAF45A8192780AA8760B02C133244B7A41D29AB74798C015546E90C5
9/26/2025 10:48:10 PM:948 --[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx) baseVersionHash = 756BC2860AF719D8DB3F441E42FC59D2F3F88F699DD0021AD49D71256D930889
9/26/2025 10:48:10 PM:949 -- status message: Saving database…
9/26/2025 10:48:10 PM:949 -- Conflict. True True True
9/26/2025 10:48:12 PM:773 -- status submessage: Merging changes…
9/26/2025 10:48:12 PM:775 -- Starting to load KDBX file...
9/26/2025 10:48:13 PM:9 -- ReadXmlStreamed: 159ms
9/26/2025 10:48:13 PM:18 -- Finished loading KDBX file.
9/26/2025 10:48:13 PM:33 -- status submessage: 
9/26/2025 10:48:13 PM:222 -- Xml WriteDocument: 105ms
9/26/2025 10:48:13 PM:224 --[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx) isCached = True
9/26/2025 10:48:14 PM:209 -- Rename/Move failed for[ https://webdav.example.com/KeePassDB.kdbx.tmp.28377870](https://webdav.example.com/KeePassDB.kdbx.tmp.28377870) to[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx): 502 
9/26/2025 10:48:14 PM:215 -- couldn't save to remote[ https://KeeUser:EoSXB4UfhcGpW_EHIrmJrCTGN@webdav.example.com/KeePassDB.kdbx](https://KeeUser:EoSXB4UfhcGpW_EHIrmJrCTGN@webdav.example.com/KeePassDB.kdbx)
9/26/2025 10:48:14 PM:216 -- System.Exception: Rename/Move failed for[ https://webdav.example.com/KeePassDB.kdbx.tmp.28377870](https://webdav.example.com/KeePassDB.kdbx.tmp.28377870) to[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx): 502 
 ---> Java.Lang.Exception: Rename/Move failed for[ https://webdav.example.com/KeePassDB.kdbx.tmp.28377870](https://webdav.example.com/KeePassDB.kdbx.tmp.28377870) to[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx): 502 
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Keepass2android.Javafilestorage.WebDavStorage.UploadFile(String path, Byte[] data, Boolean writeTransactional)
   at[ keepass2android.Io](http://keepass2android.io/).JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
  --- End of managed Java.Lang.Exception stack trace ---
java.lang.Exception: Rename/Move failed for[ https://webdav.example.com/KeePassDB.kdbx.tmp.28377870](https://webdav.example.com/KeePassDB.kdbx.tmp.28377870) to[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx): 502 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:250)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:282)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1119)

  --- End of managed Java.Lang.Exception stack trace ---
java.lang.Exception: Rename/Move failed for[ https://webdav.example.com/KeePassDB.kdbx.tmp.28377870](https://webdav.example.com/KeePassDB.kdbx.tmp.28377870) to[ https://webdav.example.com/KeePassDB.kdbx](https://webdav.example.com/KeePassDB.kdbx): 502 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:250)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:282)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1119)

   Exception_EndOfInnerExceptionStack
   at[ keepass2android.Io](http://keepass2android.io/).JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
   at[ keepass2android.Io](http://keepass2android.io/).CachingFileStorage.UpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
   at[ keepass2android.Io](http://keepass2android.io/).CachingFileStorage.TryUpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
9/26/2025 10:48:20 PM:626 -- GroupActivity.OnPause 54
9/26/2025 10:48:20 PM:627 -- Timeout start
9/26/2025 10:48:20 PM:638 -- DatabaseSettingsActivity.OnCreate 55
9/26/2025 10:48:20 PM:638 -- DatabaseSettingsActivity:apptask= 55
9/26/2025 10:48:20 PM:638 -- Secure display disabled by user preference.
9/26/2025 10:48:20 PM:642 -- DatabaseSettingsActivity.OnStart 55
9/26/2025 10:48:20 PM:643 -- DatabaseSettingsActivity.OnResume 55
9/26/2025 10:48:20 PM:643 --  DatabaseIsUnlocked=True 55
9/26/2025 10:48:20 PM:643 -- Timeout cancel
9/26/2025 10:48:21 PM:153 -- GroupActivity.OnStop 54
```

**Comment by PhilippC** [comment]
@freezewind is my assumption correct that the URLs which you replaced with a dummy contain non-ascii characters?

@giopas your error is different (but occurs also when renaming). Do you have non-ascii-characters as well? Or maybe certain file permissions configured on the server which forbid renaming?

As a work-around: if you disable file-transactions in the app settings, the error should be gone (but you don't  have the benefits of file transactions). However, I'd be very interested in understanding the issue(s) and fixing them!

**Comment by giopas** [comment]
@PhilippC thanks for the quick reply. No, in my case there are no non-ascii-characters. Files permissions are correct (I even just run a 'chmod 777' just now to try again, but it worked for several years). It is correct that taking out file transactions in the App settings solves the error (but I fear it is more prone to file writing errors, I guess). How can I help you solving the issue?

Few additional information:
The file sits on a QNAP server (using a dedicated, non admin, user) served by the built-in webdav service behind a Caddy reverse proxy on a RPI.

**Comment by AfromD** [comment]
Since the newest play store update, my webdav synced database (nextcloud) got corrupted, 0 byte file. After putting in a backup, keepass still won't open the webdav file. 

Edit: switched to nextcloud file browser. That solved my sync issue, file opens again.


```
27-09-2025 11:32:01:541 -- DatabaseSettingsActivity.OnPause 33
27-09-2025 11:32:01:548 -- Timeout start
27-09-2025 11:32:01:557 -- GroupActivity.OnStart 32
27-09-2025 11:32:01:558 -- GroupActivity.OnResume 32
27-09-2025 11:32:01:558 --  DatabaseIsUnlocked=True 32
27-09-2025 11:32:01:558 -- Timeout cancel
27-09-2025 11:32:02:28 -- DatabaseSettingsActivity.OnStop 33
27-09-2025 11:32:02:32 -- DatabaseSettingsActivity.OnDestroyTrue 33
27-09-2025 11:32:05:813 -- GroupActivity.OnPause 32
27-09-2025 11:32:05:813 -- Timeout start
27-09-2025 11:32:05:822 -- SelectCurrentDbActivity.OnStart 31
27-09-2025 11:32:05:824 -- SelectCurrentDbActivity 31: OnActivityResult FirstUser/0
27-09-2025 11:32:05:824 -- AppTask keepass2android.NullTask in OnActivityResult
27-09-2025 11:32:05:825 -- Task in activity SelectCurrentDbActivity 31 changed to NullTask
27-09-2025 11:32:05:827 -- Task in activity SelectCurrentDbActivity 31 changed to NullTask
27-09-2025 11:32:05:828 -- Finishing SelectCurrentDbActivity 31
27-09-2025 11:32:05:830 -- Finishing SelectCurrentDbActivity 31
27-09-2025 11:32:06:491 -- GroupActivity.OnStop 32
27-09-2025 11:32:06:495 -- GroupActivity.OnDestroyTrue 32
27-09-2025 11:32:06:614 -- SelectCurrentDbActivity.OnStop 31
27-09-2025 11:32:06:615 -- SelectCurrentDbActivity.OnDestroyTrue 31
27-09-2025 11:32:08:7 -- KeePass.OnCreate 34
27-09-2025 11:32:08:7 -- KeePass:apptask= 34
27-09-2025 11:32:08:7 -- Loaded task keepass2android.NullTask
27-09-2025 11:32:08:8 -- Task in activity KeePass 34 changed to NullTask
27-09-2025 11:32:08:8 -- KeePass.OnCreate
27-09-2025 11:32:08:10 -- KeePass.OnStart 34
27-09-2025 11:32:08:10 -- KeePass.OnStart
27-09-2025 11:32:08:28 -- SelectCurrentDbActivity.OnCreate 35
27-09-2025 11:32:08:28 -- SelectCurrentDbActivity:apptask= 35
27-09-2025 11:32:08:31 -- Loaded task keepass2android.NullTask
27-09-2025 11:32:08:32 -- Task in activity SelectCurrentDbActivity 35 changed to NullTask
27-09-2025 11:32:08:33 -- SelectCurrentDbActivity.OnStart 35
27-09-2025 11:32:08:34 -- SelectCurrentDbActivity.OnResume 35
27-09-2025 11:32:08:34 --  DatabaseIsUnlocked=True 35
27-09-2025 11:32:08:39 -- SelectCurrentDbActivity.OnPause 35
27-09-2025 11:32:08:46 -- GroupActivity.OnCreate 36
27-09-2025 11:32:08:46 -- GroupActivity:apptask= 36
27-09-2025 11:32:08:47 -- Setting FLAG_SECURE.
27-09-2025 11:32:08:48 -- Loaded task keepass2android.NullTask
27-09-2025 11:32:08:48 -- Task in activity GroupActivity 36 changed to NullTask
27-09-2025 11:32:08:66 -- GroupActivity.OnStart 36
27-09-2025 11:32:08:67 -- GroupActivity.OnResume 36
27-09-2025 11:32:08:67 --  DatabaseIsUnlocked=True 36
27-09-2025 11:32:08:67 -- Timeout cancel
27-09-2025 11:32:08:360 -- KeePass.OnStop 34
27-09-2025 11:32:08:360 -- KeePass.OnDestroyTrue
27-09-2025 11:32:08:360 -- KeePass.OnDestroyTrue 34
27-09-2025 11:32:08:364 -- SelectCurrentDbActivity.OnStop 35
27-09-2025 11:32:12:391 -- GroupActivity.OnPause 36
27-09-2025 11:32:12:392 -- Timeout start
27-09-2025 11:32:12:400 -- SelectCurrentDbActivity.OnStart 35
27-09-2025 11:32:12:402 -- SelectCurrentDbActivity 35: OnActivityResult 11/0
27-09-2025 11:32:12:402 -- AppTask keepass2android.NullTask in OnActivityResult
27-09-2025 11:32:12:402 -- Task in activity SelectCurrentDbActivity 35 changed to NullTask
27-09-2025 11:32:12:410 -- SelectCurrentDbActivity.OnResume 35
27-09-2025 11:32:12:410 --  DatabaseIsUnlocked=True 35
27-09-2025 11:32:12:410 -- SelectCurrentDbActivity.OnResume 35
27-09-2025 11:32:12:410 --  DatabaseIsUnlocked=True 35
27-09-2025 11:32:12:440 -- SelectCurrentDbActivity.OnPause 35
27-09-2025 11:32:12:460 -- FileSelect.OnCreate
27-09-2025 11:32:12:489 -- FileSelect.OnStart
27-09-2025 11:32:12:490 -- FileSelect.OnResume
27-09-2025 11:32:12:978 -- GroupActivity.OnStop 36
27-09-2025 11:32:12:980 -- GroupActivity.OnDestroyTrue 36
27-09-2025 11:32:13:17 -- SelectCurrentDbActivity.OnStop 35
27-09-2025 11:32:13:673 -- https://cloud.xxxx.com/remote.php/webdav/Keepass/xxxx.kbdx isCached = False
27-09-2025 11:32:13:700 -- PasswordActivity.OnDestroyTrue 29
27-09-2025 11:32:13:734 -- FileSelect.OnPause
27-09-2025 11:32:13:741 -- PasswordActivity.OnCreate 37
27-09-2025 11:32:13:741 -- PasswordActivity:apptask= 37
27-09-2025 11:32:13:742 -- Setting FLAG_SECURE.
27-09-2025 11:32:13:764 -- GetIocFromLaunchIntent()
27-09-2025 11:32:13:764 -- no keyprovider specified
27-09-2025 11:32:13:764 -- PasswordActivity: key file type KeyFile%40content%3A%2F%2Fcom.android.externalstorage.documents%2Fdocument%2Fprimary%253AKeepass%252Fxxxx.key%40N%40%40
27-09-2025 11:32:13:765 -- Added key file of length 98
27-09-2025 11:32:13:765 -- PasswordActivity: key file type 
27-09-2025 11:32:13:800 -- PasswordActivity.OnStart 37
27-09-2025 11:32:13:802 -- PasswordActivity.OnResume 37
27-09-2025 11:32:13:802 --  DatabaseIsUnlocked=True 37
27-09-2025 11:32:13:802 -- Timeout cancel
27-09-2025 11:32:13:803 -- starting: True, Finishing: False, _performingLoad: False
27-09-2025 11:32:13:804 -- https://cloud.xxxx.com/remote.php/webdav/Keepass/xxxx.kbdx isCached = False
27-09-2025 11:32:13:805 -- Pre-loading database file starting
27-09-2025 11:32:13:805 -- https://cloud.xxxx.com/remote.php/webdav/Keepass/xxxx.kbdx isCached = False
27-09-2025 11:32:13:805 -- CFS: OpenWhenNoLocalChanges
27-09-2025 11:32:13:845 -- PasswordModeSpinner item selected: 1
27-09-2025 11:32:13:846 -- key file length before: 
27-09-2025 11:32:13:846 -- key file length after: 98
27-09-2025 11:32:13:873 -- parsing autofillStructure...
27-09-2025 11:32:13:873 -- Parsing done
27-09-2025 11:32:13:873 -- cannot autofill
27-09-2025 11:32:14:345 -- FileSelect.OnStop
27-09-2025 11:32:14:381 -- FileSelect.OnDestroyTrue
27-09-2025 11:32:19:431 -- https://cloud.xxxx.com/remote.php/webdav/Keepass/xxxx.kbdx isCached = False
27-09-2025 11:32:19:432 -- LockingActivity: OnActivityResult 
27-09-2025 11:32:19:432 -- PasswordActivity.OnActivityResult 874348/1000
27-09-2025 11:32:19:438 -- content://xxxx.key isCached = True
27-09-2025 11:32:19:438 -- LockingActivity: OnActivityResult 
27-09-2025 11:32:19:439 -- PasswordActivity.OnActivityResult 874348/1004
27-09-2025 11:32:19:445 -- content://xxxx.key isCached = True
27-09-2025 11:32:19:449 -- content://xxxx.key localVersionHash = 4033E9CA232A9E553CF2E786B25F5CD9956CBA4F45585E53E94C866DBD8
27-09-2025 11:32:19:454 -- content://xxxx.key baseVersionHash = 4033E9CA232A9E553CF2E786B25F5CD9956CBA45585E53E94C866DBD8
27-09-2025 11:32:19:455 -- CFS: OpenWhenNoLocalChanges
27-09-2025 11:32:19:455 -- CFS: hashing cached version
27-09-2025 11:32:19:499 -- CFS: Files in Sync
27-09-2025 11:32:19:511 -- status message: Initializing...
27-09-2025 11:32:19:511 -- status submessage: 
27-09-2025 11:32:19:546 -- status message: Database wordt geladen…
27-09-2025 11:32:20:286 -- https://cloud.xxxx.com/remote.php/webdav/Keepass/xxxx.kbdx isCached = False
27-09-2025 11:32:20:296 -- System.IO.FileNotFoundException: 
 ---> Java.IO.FileNotFoundException: Exception_WasThrown, Java.IO.FileNotFoundException
   at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String , IJavaPeerable , JniArgumentValue* )
   at Keepass2android.Javafilestorage.WebDavStorage.OpenFileForRead(String path)
   at keepass2android.Io.JavaFileStorage.OpenFileForRead(IOConnectionInfo ioc)
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
	at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:505)
	at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:158)

  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException
	at keepass2android.javafilestorage.WebDavStorage.checkStatus(WebDavStorage.java:505)
	at keepass2android.javafilestorage.WebDavStorage.openFileForRead(WebDavStorage.java:158)

   at keepass2android.Io.JavaFileStorage.OpenFileForRead(IOConnectionInfo ioc)
   at keepass2android.Io.OfflineSwitchableFileStorage.OpenFileForRead(IOConnectionInfo ioc)
   at keepass2android.Io.CachingFileStorage.UpdateCacheFromRemote(IOConnectionInfo ioc, String cachedFilePath)
   at keepass2android.Io.CachingFileStorage.OpenFileForReadWhenNoLocalChanges(IOConnectionInfo ioc, String cachedFilePath)
   at keepass2android.Io.CachingFileStorage.OpenFileForRead(IOConnectionInfo ioc)
   at keepass2android.PasswordActivity.PreloadDbFile()
   at System.Threading.Tasks.Task`1[[System.IO.MemoryStream, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__292_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object )
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread )
27-09-2025 11:32:35:188 -- PasswordActivity.OnPause 37
27-09-2025 11:32:35:189 -- Timeout start
27-09-2025 11:32:35:219 -- AppSettingsActivity.OnCreate 38
27-09-2025 11:32:35:220 -- AppSettingsActivity:apptask= 38
27-09-2025 11:32:35:224 -- AppSettingsActivity.OnStart 38
27-09-2025 11:32:35:224 -- AppSettingsActivity.OnResume 38
27-09-2025 11:32:35:224 --  DatabaseIsUnlocked=True 38
27-09-2025 11:32:35:225 -- Timeout cancel
27-09-2025 11:32:35:720 -- PasswordActivity.OnStop 37

```

**Comment by freezewind** [comment]
@PhilippC 
Yes. My URLs contain non-ascii characters, but my another phone (Android 13) is using the same URLs without any problem. Do you have any idea?

Edit: I just found the URLs in my another phone is URL encoded. I changed the my URLs to URL encoded URLs and problem solved. 
I have a question that why the application only URL encodes the non-ascii characters in my another phone. Two behaviors with the same URLs.
Is it possible to URL encodes the non-ascii characters in URLs and header before call UpdateRemoteFile if WebDAV protocol is using? So users don't need to change the URLs by themselves.

**Comment by julnobugs** [comment]
> Since the newest play store update, my webdav synced database (nextcloud) got corrupted, 0 byte file. After putting in a backup, keepass still won't open the webdav file.

I did identify the exact same issue. If synced from keepass2android via webdav to my nextcloud (which was working for years), the DB file sent is now a 0 byte file. I was able to reproduce the issue consistently:
1. Open the DB from Keepass2Android via it's webdav URL
2. The DB is opening successfully
3.  Add an entry and save it <- this last step automatically synchronize the DB via webdav but it actually fails to synchronize as the remote DB file is now totally empty.

**Comment by AfromD** [comment]
My problem was not solved after all, it got deleted again after updating a value. What I also noticed, is that I am losing my version history on Nextcloud because updates now seem to go via a temp file, which is then deleted.

**Comment by PhilippC** [comment]
@freezewind I'll check how I can fix this. It should work without you URL-encoding the URL :-) 

@julnobugs Please switch to https://github.com/PhilippC/keepass2android/releases/tag/v1.14-r1 to get a fix immediately.

@AfromD Not sure what you mean with "it got deleted". IPlease make sure to run [1.14-r1](https://github.com/PhilippC/keepass2android/releases/tag/v1.14-r1) if the file becomes empty. Version history might be related to file transactions - thye upload to a temporary file, then rename to the actual file. You can turn this off if you can rely on Nextcloud versioning or other backups.

**Comment by AfromD** [comment]
My problem got fixed with https://github.com/PhilippC/keepass2android/issues/3032 1.14-r1

**Comment by ArthurGarnier** [comment]
I had 502 too through Apache httpd WebDAV. I had to disable File Transactions to make it works again. (On 1.14-r1)

**Comment by BotByPassion** [comment]
Hello PhilippC, 

I’d like to report the problem as the thread creator. Since version 1.14-r0, two of my smartphones have issues communicating correctly with WebDav. Attached my log:

```
30.09.2025 22:06:15:541 -- AppSettingsActivity.OnPause 2
30.09.2025 22:06:15:551 -- FileSelect.OnStart
30.09.2025 22:06:15:552 -- FileSelect.OnResume
30.09.2025 22:06:15:851 -- AppSettingsActivity.OnStop 2
30.09.2025 22:06:15:853 -- AppSettingsActivity.OnDestroyTrue 2
30.09.2025 22:06:18:959 -- FileSelect.OnPause
30.09.2025 22:06:18:966 -- SelectStorageLocationActivity.OnCreate
30.09.2025 22:06:19:461 -- FileSelect.OnStop
30.09.2025 22:06:21:323 -- onAR
30.09.2025 22:06:21:324 -- base.onAR
30.09.2025 22:06:47:210 -- FileSelect.OnStart
30.09.2025 22:06:47:245 -- PasswordActivity.OnCreate 3
30.09.2025 22:06:47:245 -- PasswordActivity:apptask= 3
30.09.2025 22:06:47:248 -- Setting FLAG_SECURE.
30.09.2025 22:06:47:281 -- GetIocFromLaunchIntent()
30.09.2025 22:06:47:281 -- no keyprovider specified
30.09.2025 22:06:47:282 -- Reset keyfile
30.09.2025 22:06:47:288 -- PasswordActivity.OnStart 3
30.09.2025 22:06:47:295 -- PasswordActivity.OnResume 3
30.09.2025 22:06:47:295 --  DB null 3
30.09.2025 22:06:47:295 -- starting: True, Finishing: False, _performingLoad: False
30.09.2025 22:06:47:295 -- https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx isCached = False
30.09.2025 22:06:47:299 -- Pre-loading database file starting
30.09.2025 22:06:47:299 -- https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx isCached = False
30.09.2025 22:06:47:300 -- CFS: OpenWhenNoLocalChanges
30.09.2025 22:06:47:362 -- PasswordModeSpinner item selected: 0
30.09.2025 22:06:47:648 -- FileSelect.OnStop
30.09.2025 22:06:47:671 -- FileSelect.OnDestroyTrue
30.09.2025 22:06:48:834 -- CFS: Updated Cache
30.09.2025 22:06:48:843 -- Pre-loading database file completed
30.09.2025 22:06:50:973 -- PasswordModeSpinner item selected: 1
30.09.2025 22:06:50:974 -- key file length before: 
30.09.2025 22:06:50:974 -- key file length after: 0
30.09.2025 22:06:52:511 -- PasswordActivity.OnPause 3
30.09.2025 22:06:52:519 -- SelectStorageLocationActivity.OnCreate
30.09.2025 22:06:52:938 -- PasswordActivity.OnStop 3
30.09.2025 22:06:54:315 -- onAR
30.09.2025 22:06:54:315 -- base.onAR
30.09.2025 22:06:54:319 -- com.android.documentsui
30.09.2025 22:06:54:319 -- com.mixplorer
30.09.2025 22:07:01:581 -- onAR
30.09.2025 22:07:01:581 -- base.onAR
30.09.2025 22:07:01:591 -- TakePersistableUriPermission
30.09.2025 22:07:01:606 -- PasswordActivity.OnStart 3
30.09.2025 22:07:01:607 -- LockingActivity: OnActivityResult 
30.09.2025 22:07:01:607 -- PasswordActivity.OnActivityResult Ok/1003
30.09.2025 22:07:01:607 -- Set keyfile after returning from RequestCodeSelectKeyfile
30.09.2025 22:07:01:616 -- PasswordActivity.OnResume 3
30.09.2025 22:07:01:616 --  DB null 3
30.09.2025 22:07:01:617 -- starting: True, Finishing: False, _performingLoad: False
30.09.2025 22:07:01:617 -- https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx isCached = True
30.09.2025 22:07:03:739 -- PasswordActivity.OnPause 3
30.09.2025 22:07:03:752 -- PasswordActivity.OnStop 3
30.09.2025 22:07:08:128 -- PasswordActivity.OnStart 3
30.09.2025 22:07:08:129 -- PasswordActivity.OnResume 3
30.09.2025 22:07:08:129 --  DB null 3
30.09.2025 22:07:08:129 -- starting: True, Finishing: False, _performingLoad: False
30.09.2025 22:07:08:129 -- https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx isCached = True
30.09.2025 22:07:11:695 -- https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx isCached = True
30.09.2025 22:07:11:697 -- LockingActivity: OnActivityResult 
30.09.2025 22:07:11:697 -- PasswordActivity.OnActivityResult 874348/1000
30.09.2025 22:07:11:702 -- content://Test-Keeps2Android.keyx isCached = False
30.09.2025 22:07:11:702 -- LockingActivity: OnActivityResult 
30.09.2025 22:07:11:703 -- PasswordActivity.OnActivityResult 874348/1004
30.09.2025 22:07:11:774 -- content://Test-Keeps2Android.keyx isCached = False
30.09.2025 22:07:11:774 -- CFS: OpenWhenNoLocalChanges
30.09.2025 22:07:11:794 -- CFS: Updated Cache
30.09.2025 22:07:11:905 -- status message: Initializing...
30.09.2025 22:07:11:906 -- status submessage: 
30.09.2025 22:07:11:931 -- status message: Lade Datenbank…
30.09.2025 22:07:11:936 -- LoadDb: Copying database in memory
30.09.2025 22:07:11:936 -- LoadDb: Ready to start loading
30.09.2025 22:07:11:937 -- LoadDb: Copying database for backup
30.09.2025 22:07:11:937 -- LoadDb: Checking open databases
30.09.2025 22:07:11:943 -- LoadData: Retrieving stream
30.09.2025 22:07:11:943 -- LoadData: GetCurrentFileVersion
30.09.2025 22:07:11:943 -- LoadData: PopulateDatabaseFromStream
30.09.2025 22:07:11:948 -- Starting to load KDBX file...
30.09.2025 22:07:11:952 -- status submessage: Schlüsseltransformationen werden durchgeführt …
30.09.2025 22:07:12:26 -- status submessage: Lese Datenbank ein…
30.09.2025 22:07:12:41 -- ReadXmlStreamed: 13ms
30.09.2025 22:07:12:43 -- Finished loading KDBX file.
30.09.2025 22:07:12:43 -- status submessage: 
30.09.2025 22:07:12:44 -- status message: Lokale Sicherung wird aktualisiert …
30.09.2025 22:07:12:49 -- Timeout cancel
30.09.2025 22:07:12:51 -- LoadDB OK
30.09.2025 22:07:12:97 -- Starting/Updating OngoingNotificationsService. Database Unlocked
30.09.2025 22:07:12:106 -- PasswordActivity.OnPause 3
30.09.2025 22:07:12:106 -- Timeout start
30.09.2025 22:07:12:111 -- SelectCurrentDbActivity.OnStart 1
30.09.2025 22:07:12:112 -- SelectCurrentDbActivity 1: OnActivityResult Ok/1
30.09.2025 22:07:12:112 -- No AppTask in OnActivityResult
30.09.2025 22:07:12:117 -- SelectCurrentDbActivity.OnResume 1
30.09.2025 22:07:12:117 --  DatabaseIsUnlocked=True 1
30.09.2025 22:07:12:118 -- SelectCurrentDbActivity.OnResume 1
30.09.2025 22:07:12:118 --  DatabaseIsUnlocked=True 1
30.09.2025 22:07:12:121 -- SelectCurrentDbActivity.OnPause 1
30.09.2025 22:07:12:144 -- GroupActivity.OnCreate 4
30.09.2025 22:07:12:144 -- GroupActivity:apptask= 4
30.09.2025 22:07:12:144 -- Setting FLAG_SECURE.
30.09.2025 22:07:12:144 -- Loaded task keepass2android.NullTask
30.09.2025 22:07:12:144 -- Task in activity GroupActivity 4 changed to NullTask
30.09.2025 22:07:12:158 -- GroupActivity.OnStart 4
30.09.2025 22:07:12:159 -- GroupActivity.OnResume 4
30.09.2025 22:07:12:159 --  DatabaseIsUnlocked=True 4
30.09.2025 22:07:12:159 -- Timeout cancel
30.09.2025 22:07:12:499 -- PasswordActivity.OnStop 3
30.09.2025 22:07:12:500 -- PasswordActivity.OnDestroyTrue 3
30.09.2025 22:07:12:526 -- SelectCurrentDbActivity.OnStop 1
30.09.2025 22:07:18:457 -- GroupActivity.OnPause 4
30.09.2025 22:07:18:457 -- Timeout start
30.09.2025 22:07:18:467 -- GroupActivity.OnCreate 5
30.09.2025 22:07:18:467 -- GroupActivity:apptask= 5
30.09.2025 22:07:18:467 -- Setting FLAG_SECURE.
30.09.2025 22:07:18:468 -- Loaded task keepass2android.NullTask
30.09.2025 22:07:18:468 -- Task in activity GroupActivity 5 changed to NullTask
30.09.2025 22:07:18:477 -- GroupActivity.OnStart 5
30.09.2025 22:07:18:478 -- GroupActivity.OnResume 5
30.09.2025 22:07:18:478 --  DatabaseIsUnlocked=True 5
30.09.2025 22:07:18:478 -- Timeout cancel
30.09.2025 22:07:18:883 -- GroupActivity.OnStop 4
30.09.2025 22:07:25:47 -- GroupActivity.OnPause 5
30.09.2025 22:07:25:47 -- Timeout start
30.09.2025 22:07:25:55 -- EntryEditActivity.OnCreate 6
30.09.2025 22:07:25:55 -- EntryEditActivity:apptask= 6
30.09.2025 22:07:25:56 -- Setting FLAG_SECURE.
30.09.2025 22:07:25:60 -- Loaded task keepass2android.NullTask
30.09.2025 22:07:25:60 -- Task in activity EntryEditActivity 6 changed to NullTask
30.09.2025 22:07:25:89 -- EntryEditActivity.OnStart 6
30.09.2025 22:07:25:90 -- EntryEditActivity.OnResume 6
30.09.2025 22:07:25:90 --  DatabaseIsUnlocked=True 6
30.09.2025 22:07:25:90 -- Timeout cancel
30.09.2025 22:07:25:488 -- GroupActivity.OnStop 5
30.09.2025 22:07:40:91 -- status message: Initializing...
30.09.2025 22:07:40:91 -- status submessage: 
30.09.2025 22:07:40:106 -- status message: Eintrag wird hinzugefügt …
30.09.2025 22:07:40:108 -- status message: Speichere Datenbank…
30.09.2025 22:07:40:108 -- status submessage: Prüfen, ob Zieldatei geändert wurde …
30.09.2025 22:07:41:162 -- status submessage: 
30.09.2025 22:07:41:265 -- Xml WriteDocument: 32ms
30.09.2025 22:07:41:265 -- https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx isCached = True
30.09.2025 22:07:43:521 -- Rename/Move failed for https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx.tmp.39688512 to https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx: 400 
30.09.2025 22:07:43:529 -- couldn't save to remote https://user:pass@my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx
30.09.2025 22:07:43:530 -- System.Exception: Rename/Move failed for https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx.tmp.39688512 to https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx: 400 
 ---> Java.Lang.Exception: Rename/Move failed for https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx.tmp.39688512 to https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx: 400 
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Keepass2android.Javafilestorage.WebDavStorage.UploadFile(String path, Byte[] data, Boolean writeTransactional)
   at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
  --- End of managed Java.Lang.Exception stack trace ---
java.lang.Exception: Rename/Move failed for https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx.tmp.39688512 to https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx: 400 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:236)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:268)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1042)

  --- End of managed Java.Lang.Exception stack trace ---
java.lang.Exception: Rename/Move failed for https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx.tmp.39688512 to https://my.domain/webdav/Test-Keeps2Android/Test-Keeps2Android.kdbx: 400 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:236)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:268)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:1042)

   Exception_EndOfInnerExceptionStack
   at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
   at keepass2android.Io.CachingFileStorage.TryUpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
30.09.2025 22:07:43:546 -- EntryEditActivity.OnPause 6
30.09.2025 22:07:43:547 -- Timeout start
30.09.2025 22:07:43:553 -- GroupActivity.OnStart 5
30.09.2025 22:07:43:554 -- LockingActivity: OnActivityResult 
30.09.2025 22:07:43:554 -- TryGetFromActivityResult: no data
30.09.2025 22:07:43:554 -- GroupActivity.OnResume 5
30.09.2025 22:07:43:554 --  DatabaseIsUnlocked=True 5
30.09.2025 22:07:43:554 -- Timeout cancel
30.09.2025 22:07:43:858 -- EntryEditActivity.OnStop 6
30.09.2025 22:07:43:859 -- EntryEditActivity.OnDestroyTrue 6
30.09.2025 22:07:55:495 -- GroupActivity.OnPause 5
30.09.2025 22:07:55:495 -- Timeout start
30.09.2025 22:07:55:507 -- DatabaseSettingsActivity.OnCreate 7
30.09.2025 22:07:55:507 -- DatabaseSettingsActivity:apptask= 7
30.09.2025 22:07:55:507 -- Setting FLAG_SECURE.
30.09.2025 22:07:55:509 -- DatabaseSettingsActivity.OnStart 7
30.09.2025 22:07:55:510 -- DatabaseSettingsActivity.OnResume 7
30.09.2025 22:07:55:510 --  DatabaseIsUnlocked=True 7
30.09.2025 22:07:55:510 -- Timeout cancel
30.09.2025 22:07:55:902 -- GroupActivity.OnStop 5
30.09.2025 22:08:03:954 -- DatabaseSettingsActivity.OnPause 7
30.09.2025 22:08:03:955 -- Timeout start
30.09.2025 22:08:10:677 -- DatabaseSettingsActivity.OnStop 7
30.09.2025 22:08:23:684 -- DatabaseSettingsActivity.OnStart 7
30.09.2025 22:08:23:686 -- DatabaseSettingsActivity.OnResume 7
30.09.2025 22:08:23:686 --  DatabaseIsUnlocked=True 7
30.09.2025 22:08:23:686 -- Timeout cancel
```

The customized URL "my.domain" consists exclusively of aphanumeric characters and a separator and does not contain any "non-ASCII characters" such as umlauts (ä, ö, ü) or special characters from other writing systems.

The user that connects to the database also consists exclusively of alphanumeric characters and a separator, and does not contain any "non-ASCII characters" such as umlauts (ä, ö, ü) or special characters from other writing systems.

The password consists of a mixture of letters, digits, and a range of special characters. Although this string contains numerous special characters, technically it is a pure ASCII string. It does not contain any "non-ASCII characters" such as umlauts (ä, ö, ü), accents (é, è), or characters from non-Latin alphabets (such as Greek, Cyrillic, etc.).

Both phones use Android 15.

I conducted a test last night with version 1.13-r1, and everything worked without any issues.

Disabling file transactions does help prevent the error from occurring, but it’s more likely a workaround than a solution, isn’t it?

Sure, I hope you can find the issue :)

Have a nice day

**Comment by outerSpaceToast** [comment]
Similar problem here:"Unexpected char 0xfc at 47 in Destination value: ..."
The corresponding character in the (Nextcloud Webdav) path is a "ü".
I'm already using version 1.14-r1.


This has worked for years and now it stopped.

**Comment by MrMu666** [comment]
Since version 1.14-r0,  WebDAV no longer synchronizes data normally as it did in previous versions.

**Comment by MrMu666** [comment]
1.14-r0 and 1.14-r1 have the similar problem on my android14 phone.

**Comment by pjbondi** [comment]
Hello to all:

In our family, we have a Subversion server on QNAP.  We all use Keepass2Android on our phones.  So we have backups of our previous versions of our Keepass databases.  The screen capture shows 3 Keepass database subversion histories for 3 different family members.

Starting Sep. 26, it appears to me that the Keepass2Android save algorithm for WebDAV was somehow changed from a WebDAV update to create, rename.  See screen capture that shows commits that are all updates, until Sep. 26

![Image](https://github.com/user-attachments/assets/53986bbb-d04c-456d-bc2e-6102e8e3ccff)

**Comment by idzyr** [comment]
I also encountered synchronization issues, but it's not character-related. I tested v1.13-r3, which can synchronize normally, but later versions exhibit the following problems.

```
2025/10/12 下午10:26:50:259 -- DatabaseSettingsActivity.OnPause 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:26:50:262 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:26:51:399 -- DatabaseSettingsActivity.OnResume 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:26:51:400 --  DatabaseIsUnlocked=True 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:26:51:401 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:26:52:488 -- DatabaseSettingsActivity.OnPause 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:26:52:489 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:07:104 -- Going to background (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:07:105 -- DatabaseSettingsActivity.OnStop 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:14:776 -- DatabaseSettingsActivity.OnStart 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:14:777 -- Going to foreground (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:14:782 -- DatabaseSettingsActivity.OnResume 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:14:783 --  DatabaseIsUnlocked=True 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:14:784 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:18:50 -- DatabaseSettingsActivity.OnPause 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:18:51 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:18:89 -- DatabaseSettingsActivity.OnStop 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:18:752 -- Going to background (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:42:178 -- DatabaseSettingsActivity.OnStart 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:42:179 -- Going to foreground (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:42:185 -- DatabaseSettingsActivity.OnResume 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:42:186 --  DatabaseIsUnlocked=True 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:42:187 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:44:275 -- DatabaseSettingsActivity.OnPause 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:44:276 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:44:319 -- DatabaseSettingsActivity.OnStop 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:44:977 -- Going to background (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:51:712 -- DatabaseSettingsActivity.OnStart 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:51:713 -- Going to foreground (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:51:718 -- DatabaseSettingsActivity.OnResume 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:51:720 --  DatabaseIsUnlocked=True 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:51:720 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:56:715 -- DatabaseSettingsActivity.OnPause 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:56:716 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:56:733 -- GroupActivity.OnStart 6 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:56:737 -- GroupActivity.OnResume 6 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:56:738 --  DatabaseIsUnlocked=True 6 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:56:738 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:57:126 -- DatabaseSettingsActivity.OnStop 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:27:57:141 -- DatabaseSettingsActivity.OnDestroy True 8 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:04:744 -- Checking for file change. Current hash = 1C8F26DDC6E62283328E5D84E78B68CB6DC28718D072655EC4AE6212789CE873 (Thread ID: 17)
2025/10/12 下午10:28:04:745 -- https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx baseVersionHash = 1C8F26DDC6E62283328E5D84E78B68CB6DC28718D072655EC4AE6212789CE873 (Thread ID: 17)
2025/10/12 下午10:28:04:746 -- Checking for file change. baseVersionHash = 1C8F26DDC6E62283328E5D84E78B68CB6DC28718D072655EC4AE6212789CE873 (Thread ID: 17)
2025/10/12 下午10:28:04:751 -- https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx isCached = True (Thread ID: 17)
2025/10/12 下午10:28:04:754 -- https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx localVersionHash = B7F0CFC1FE1A0DDDAA583DC475902DB0D10C0C4ECC2FFFB852B5186F077E2B31 (Thread ID: 17)
2025/10/12 下午10:28:04:757 -- https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx baseVersionHash = 1C8F26DDC6E62283328E5D84E78B68CB6DC28718D072655EC4AE6212789CE873 (Thread ID: 17)
2025/10/12 下午10:28:04:760 -- https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx localVersionHash = B7F0CFC1FE1A0DDDAA583DC475902DB0D10C0C4ECC2FFFB852B5186F077E2B31 (Thread ID: 17)
2025/10/12 下午10:28:04:923 -- Rename/Move failed for https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx.tmp.27665974 to https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx: 409  (Thread ID: 17)
2025/10/12 下午10:28:04:928 -- System.Exception: Rename/Move failed for https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx.tmp.27665974 to https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx: 409 
 ---> Java.Lang.Exception: Rename/Move failed for https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx.tmp.27665974 to https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx: 409 
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Keepass2android.Javafilestorage.WebDavStorage.UploadFile(String path, Byte[] data, Boolean writeTransactional)
   at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
  --- End of managed Java.Lang.Exception stack trace ---
java.lang.Exception: Rename/Move failed for https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx.tmp.27665974 to https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx: 409 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:236)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:268)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:764)

  --- End of managed Java.Lang.Exception stack trace ---
java.lang.Exception: Rename/Move failed for https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx.tmp.27665974 to https://dav.jianguoyun.com/dav/KeepPassTest/Pass.kdbx: 409 
	at keepass2android.javafilestorage.WebDavStorage.renameOrMoveWebDavResource(WebDavStorage.java:236)
	at keepass2android.javafilestorage.WebDavStorage.uploadFile(WebDavStorage.java:268)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:764)

   Exception_EndOfInnerExceptionStack
   at keepass2android.Io.JavaFileStorage.JavaFileStorageWriteTransaction.CommitWrite()
   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(Stream cachedData, IOConnectionInfo ioc, Boolean useFileTransaction, String hash)
   at keepass2android.Io.CachingFileStorage.UpdateRemoteFile(IOConnectionInfo ioc, Boolean useFileTransaction)
   at keepass2android.SynchronizeCachedDatabase.Run() (Thread ID: 17)
2025/10/12 下午10:28:08:548 -- GroupActivity.OnPause 6 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:548 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:580 -- DatabaseSettingsActivity.OnCreate 9 (instance=9) (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:581 -- DatabaseSettingsActivity:apptask= 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:582 -- Setting FLAG_SECURE. (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:594 -- DatabaseSettingsActivity.OnStart 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:597 -- DatabaseSettingsActivity.OnResume 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:598 --  DatabaseIsUnlocked=True 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:598 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:08:943 -- GroupActivity.OnStop 6 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:10:396 -- DatabaseSettingsActivity.OnPause 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:10:397 -- Timeout start (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:10:809 -- DatabaseSettingsActivity.OnStop 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:12:154 -- DatabaseSettingsActivity.OnStart 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:12:156 -- DatabaseSettingsActivity.OnResume 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:12:157 --  DatabaseIsUnlocked=True 9 (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:12:157 -- Timeout cancel (Thread ID: 1) (Main Looper)
2025/10/12 下午10:28:16:756 -- Quit TriggerBackgroundSyncIfNeeded (Thread ID: 15)
```

**Comment by PhilippC** [comment]
Hi all,
sorry that this hasn' received updates in the past two weeks. Going through the whole discussion here, I think there are two kinds of errors:
 * "Unexpected char" when there is a non-ascii character in the URL. This was reported by @freezewind  and @outerSpaceToast .
 * "Rename/Move failed" with either error code 502 (@giopas  @ArthurGarnier  @BotByPassion ) or error code 409 (@idzyr).

Unfortunately, I cannot reproduce either of these two errors. Could you setup testing accounts for me on your servers (one account per test category should be enough) and share credentials to crocoapps@gmail.com?

**Comment by PhilippC** [comment]
I was able to reproduce the Unexpected char issue when I create a file with an umlaut in its name and then open it by specifying the full Webdav path manually. (If I enter just the server URL and use the built-in file picker, the filename is URL encoded and works)

@freezewind  @outerSpaceToast  can you remember how you opened the file? Did you enter the full path manually or did you enter just the server URL and then browse to the file? Because in the latter case, it should be URL encoded properly.

**Comment by freezewind** [comment]
@PhilippC Yes. I remember I entered the full path manually before.

**Comment by outerSpaceToast** [comment]
> [@freezewind](https://github.com/freezewind) [@outerSpaceToast](https://github.com/outerSpaceToast) can you remember how you opened the file? Did you enter the full path manually or did you enter just the server URL and then browse to the file? Because in the latter case, it should be URL encoded properly.

I switched my Nextcloud from http to https, so I probably just added the "s" manually. Later I selected the file via browsing in KeePass2Android, then the URL was correctly encoded.

**Comment by PhilippC** [comment]
I have published a new version on https://github.com/PhilippC/keepass2android/releases/tag/v1.15-pre1

@freezewind  @outerSpaceToast can you please verify that the issue is now fixed?

@giopas @ArthurGarnier @BotByPassion @idzyr I still wasn't able to reproduce what you described. Can you check if the behavior persists with 1.15-pre1 and if so, please try to set up a testing account for me?

**Comment by freezewind** [comment]
@PhilippC 
Great! The issue is fixed now with 1.15-pre1.

**Comment by BotByPassion** [comment]
Hey @PhilippC 

unfortunately the error regarding 'Rename/Move failed with error code' is still not resolved with the new version.

I sent you an email today with various access credentials (cloud, test database).

Email subject: [BUG] [WebDAV] Java.Lang.IllegalArgumentException: Unexpected char #3030

Please also check the Spam folder. My email address is a bit special XD

Hope it will help you locate, reproduce, test, and ultimately fix the error.

Have a nice day

**Comment by PhilippC** [comment]
This is now fixed in https://github.com/PhilippC/keepass2android/releases/tag/v1.15-pre2 thanks to @linuxhenhao !
