### ISSUE TITLE
Keepass2android hangs if it tries to access remote database but is offline 

### ISSUE THREAD

**Issue by tenders** [PhilippC/keepass2android#891]
I copied my database file to my OneDrive Directory because i want to Access it from my PC (Windows) and also from my mobile device (Android).
Both works perfectly fine if i have an Internet Connection (4G or WLAN) on my mobile phone.
On my Android device, i find a cached local copy of my database which i can open explicitely...........but only if there is a Connection to the original database in OneDrive via the Internet. 
If this isn't the case, i have the following behaviour: If i start Keepass2android, i see very shortly the blue coloured start screen of Keepass2android and after 0.5 seconds, the Screen becomes completely white. This state can only be stopped if i terminate the process, which doesn't help because if i restart Keepass2android, i face the same behaviour.
For me it seems that Keepass2android tries to find the remote database even if the Network is disabled (Flight Modus).

Is there something i can do ? Does anybody can help ? Thank you !

**Comment by PhilippC** [comment]
related: https://github.com/PhilippC/keepass2android/issues/240

**Comment by PhilippC** [comment]
should be fixed now: Please switch to beta and install 1.07b-pre2 (just published to beta, see https://play.google.com/apps/testing/keepass2android.keepass2android). Please click "Change database" (on the password screen), then "Open database", "One Drive", "All files and shared files" (or something else if appropriate) and browse to your file again. This will then use the new implementation. (If you don't re-open the database like this, the old implementation will be used).
Please re-open (or comment) if the issue persists for some reason.

**Comment by rennyavm** [comment]
I still have this issue, on 1.09a-r3.  
My database is on OneDrive, and Keepass2Android fails to load the cached copy if I'm offline. 
I get the exact behavior that OP is describing - briefly the start blue screen, then a spinner on a blank screen, with no other option but to terminate.
