### ISSUE TITLE
Crush on turning up fingerprint unlocking

### ISSUE THREAD

**Issue by lddnsk** [PhilippC/keepass2android#934]
App crushing when I turn on any variant of unlock by fingerprint

Mi Note 3 on android 8.1 (miui 10.3)

> 

> java.security.ProviderException: Keystore operation failed
>  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:321)
>  at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:604)
>  at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
>  at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
>  at android.widget.CompoundButton.setChecked(CompoundButton.java:171)
>  at android.widget.CompoundButton.toggle(CompoundButton.java:127)
>  at android.widget.RadioButton.toggle(RadioButton.java:76)
>  at android.widget.CompoundButton.performClick(CompoundButton.java:132)
>  at android.view.View$PerformClick.run(View.java:24833)
>  at android.os.Handler.handleCallback(Handler.java:794)
>  at android.os.Handler.dispatchMessage(Handler.java:99)
>  at android.os.Looper.loop(Looper.java:173)
>  at android.app.ActivityThread.main(ActivityThread.java:6653)
>  at java.lang.reflect.Method.invoke(Native Method)
>  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
> Caused by: android.security.KeyStoreException: User authentication required
>  at android.security.KeyStore.getKeyStoreException(KeyStore.java:672)
>  at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:322)
>  ... 15 more

**Comment by karottenbaum** [comment]
This happens for me too (Pixel 2, Android Q beta 5):

```logcat
08-31 19:02:05.458  2555  2555 W keepass2androi: JNI RegisterNativeMethods: attempt to register 0 native methods for md5f0702f468598c68ce18586502249fb40.FingerprintEncryption
08-31 19:02:05.458  2555  2555 D KP2A    : FP: Create FingerprintEncryption
08-31 19:02:05.471  2555  2555 D KP2A    : FP: CreateKey 
08-31 19:02:05.481 20322 20322 I keystore: del USRPKEY_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.482 20322 20322 I keystore: del USRSKEY_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.482 20322 20322 I keystore: del USRCERT_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.482 20322 20322 I keystore: del CACERT_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.490 20322  3366 W /system/bin/keystore: Trying to serialize unknown tag 1879048895. Did you forget to add it to all_tags_t?
08-31 19:02:05.490 20322  3366 D keystore: couldn't insert encrypted blob while not unlocked
08-31 19:02:05.490  2555  2555 E KeyStore: generateKeyInternal failed on response 2
08-31 19:02:05.490 20322  3366 D DropBoxManager: About to call service->add()
08-31 19:02:05.491 20322 20322 I keystore: del USRPKEY_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.491  1291  8785 I DropBoxManagerService: add tag=keymaster isTagEnabled=true flags=0x0
08-31 19:02:05.491 20322 20322 I keystore: del USRSKEY_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.491 20322 20322 I keystore: del USRCERT_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.491 20322 20322 I keystore: del CACERT_keepass2android.kp2a_ioc_XXXXXXXX 10221
08-31 19:02:05.495  1291  8785 W DropBoxManagerService: Dropping: keymaster (53 > 0 bytes)
08-31 19:02:05.495 20322  3366 D DropBoxManager: service->add returned No error
08-31 19:02:05.501  2555  2555 I MonoDroid: UNHANDLED EXCEPTION:
08-31 19:02:05.516  2555  2555 I MonoDroid: Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required
08-31 19:02:05.516  2555  2555 I MonoDroid:    --- End of inner exception stack trace ---
08-31 19:02:05.516  2555  2555 I MonoDroid:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <daf82fa226e64866b6883f2960c1a0f1>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <daf82fa226e64866b6883f2960c1a0f1>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at keepass2android.FingerprintEncryption.CreateKey () [0x00059] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at keepass2android.FingerprintEncryption..ctor (keepass2android.FingerprintModule fingerprint, System.String keyId) [0x0001e] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at keepass2android.FingerprintSetupActivity.ChangeUnlockMode (keepass2android.FingerprintUnlockMode oldMode, keepass2android.FingerprintUnlockMode newMode) [0x000b1] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at keepass2android.FingerprintSetupActivity.<OnCreate>b__8_2 (System.Object sender, Android.Widget.CompoundButton+CheckedChangeEventArgs args) [0x0004a] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at Android.Widget.CompoundButton+IOnCheckedChangeListenerImplementor.OnCheckedChanged (Android.Widget.CompoundButton buttonView, System.Boolean isChecked) [0x00012] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at Android.Widget.CompoundButton+IOnCheckedChangeListenerInvoker.n_OnCheckedChanged_Landroid_widget_CompoundButton_Z (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_buttonView, System.Boolean isChecked) [0x0000f] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
08-31 19:02:05.516  2555  2555 I MonoDroid:   at (wrapper dynamic-method) System.Object.b7a2ecd7-a1c3-4447-a264-9d42caf80e5e(intptr,intptr,intptr,bool)
08-31 19:02:05.516  2555  2555 I MonoDroid:   --- End of managed Java.Lang.RuntimeException stack trace ---
08-31 19:02:05.516  2555  2555 I MonoDroid: java.security.ProviderException: Keystore operation failed
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:332)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.widget.CompoundButton.setChecked(CompoundButton.java:180)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.widget.CompoundButton.toggle(CompoundButton.java:135)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.widget.RadioButton.toggle(RadioButton.java:76)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.widget.CompoundButton.performClick(CompoundButton.java:140)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.view.View.performClickInternal(View.java:7117)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.view.View.access$3500(View.java:801)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.view.View$PerformClick.run(View.java:27351)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.os.Handler.handleCallback(Handler.java:883)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:100)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.os.Looper.loop(Looper.java:214)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7356)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-31 19:02:05.516  2555  2555 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
08-31 19:02:05.516  2555  2555 I MonoDroid: Caused by: android.security.KeyStoreException: User authentication required
08-31 19:02:05.516  2555  2555 I MonoDroid:     at android.security.KeyStore.getKeyStoreException(KeyStore.java:1264)
08-31 19:02:05.516  2555  2555 I MonoDroid:     ... 18 more
08-31 19:02:05.516  2555  2555 I MonoDroid: 
08-31 19:02:05.519  2555  2555 D KP2A    : Java.Lang.RuntimeException: Keystore operation failed ---> Java.Lang.Exception: User authentication required
08-31 19:02:05.519  2555  2555 D KP2A    :    --- End of inner exception stack trace ---
08-31 19:02:05.519  2555  2555 D KP2A    :   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <a2068f8b3f6f40d0ad70bc362d4b0524>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <daf82fa226e64866b6883f2960c1a0f1>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <daf82fa226e64866b6883f2960c1a0f1>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at Javax.Crypto.KeyGenerator.GenerateKey () [0x0000a] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at keepass2android.FingerprintEncryption.CreateKey () [0x00059] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at keepass2android.FingerprintEncryption..ctor (keepass2android.FingerprintModule fingerprint, System.String keyId) [0x0001e] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at keepass2android.FingerprintSetupActivity.ChangeUnlockMode (keepass2android.FingerprintUnlockMode oldMode, keepass2android.FingerprintUnlockMode newMode) [0x000b1] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at keepass2android.FingerprintSetupActivity.<OnCreate>b__8_2 (System.Object sender, Android.Widget.CompoundButton+CheckedChangeEventArgs args) [0x0004a] in <42483a0e42cb482da6be36caa63cd922>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at Android.Widget.CompoundButton+IOnCheckedChangeListenerImplementor.OnCheckedChanged (Android.Widget.CompoundButton buttonView, System.Boolean isChecked) [0x00012] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at Android.Widget.CompoundButton+IOnCheckedChangeListenerInvoker.n_OnCheckedChanged_Landroid_widget_CompoundButton_Z (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_buttonView, System.Boolean isChecked) [0x0000f] in <f53e43de1d6c43078eb67fc63a0181e1>:0 
08-31 19:02:05.519  2555  2555 D KP2A    :   at (wrapper dynamic-method) System.Object.b7a2ecd7-a1c3-4447-a264-9d42caf80e5e(intptr,intptr,intptr,bool)
08-31 19:02:05.519  2555  2555 D KP2A    :   --- End of managed Java.Lang.RuntimeException stack trace ---
08-31 19:02:05.519  2555  2555 D KP2A    : java.security.ProviderException: Keystore operation failed
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:332)
08-31 19:02:05.519  2555  2555 D KP2A    :      at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
08-31 19:02:05.519  2555  2555 D KP2A    :      at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
08-31 19:02:05.519  2555  2555 D KP2A    :      at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.widget.CompoundButton.setChecked(CompoundButton.java:180)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.widget.CompoundButton.toggle(CompoundButton.java:135)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.widget.RadioButton.toggle(RadioButton.java:76)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.widget.CompoundButton.performClick(CompoundButton.java:140)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.view.View.performClickInternal(View.java:7117)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.view.View.access$3500(View.java:801)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.view.View$PerformClick.run(View.java:27351)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.os.Handler.handleCallback(Handler.java:883)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.os.Handler.dispatchMessage(Handler.java:100)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.os.Looper.loop(Looper.java:214)
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.app.ActivityThread.main(ActivityThread.java:7356)
08-31 19:02:05.519  2555  2555 D KP2A    :      at java.lang.reflect.Method.invoke(Native Method)
08-31 19:02:05.519  2555  2555 D KP2A    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-31 19:02:05.519  2555  2555 D KP2A    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
08-31 19:02:05.519  2555  2555 D KP2A    : Caused by: android.security.KeyStoreException: User authentication required
08-31 19:02:05.519  2555  2555 D KP2A    :      at android.security.KeyStore.getKeyStoreException(KeyStore.java:1264)
08-31 19:02:05.519  2555  2555 D KP2A    :      ... 18 more
08-31 19:02:05.520  2555  2555 D AndroidRuntime: Shutting down VM
08-31 19:02:05.521  2555  2555 E AndroidRuntime: FATAL EXCEPTION: main
08-31 19:02:05.521  2555  2555 E AndroidRuntime: Process: keepass2android.keepass2android, PID: 2555
08-31 19:02:05.521  2555  2555 E AndroidRuntime: java.security.ProviderException: Keystore operation failed
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:332)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.n_onCheckedChanged(Native Method)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at mono.android.widget.CompoundButton_OnCheckedChangeListenerImplementor.onCheckedChanged(CompoundButton_OnCheckedChangeListenerImplementor.java:30)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.widget.CompoundButton.setChecked(CompoundButton.java:180)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.widget.CompoundButton.toggle(CompoundButton.java:135)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.widget.RadioButton.toggle(RadioButton.java:76)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.widget.CompoundButton.performClick(CompoundButton.java:140)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7117)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.view.View.access$3500(View.java:801)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:27351)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
08-31 19:02:05.521  2555  2555 E AndroidRuntime: Caused by: android.security.KeyStoreException: User authentication required
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1264)
08-31 19:02:05.521  2555  2555 E AndroidRuntime:        ... 18 more
08-31 19:02:05.526  1291  8785 W ActivityTaskManager:   Force finishing activity keepass2android.keepass2android/md5f0702f468598c68ce18586502249fb40.FingerprintSetupActivity
```

**Comment by emilbrandt99** [comment]
Same problem. Google Pixel 2XL, official Android 10 release. Crashes application on enabling fingerprint unlock.

**Comment by PhilippC** [comment]
users have reported that there is a workaround: first try to enable fingerprint for QuickUnlock, then for full unlock. I will try to fix this anyway, of course.

**Comment by emilbrandt99** [comment]
It seems to be working now and I have no idea what I did to correct it.
Wish I could be more helpful. Thanks for getting back to me. I use k2a all
the time and it's a great app.

Eric

**Comment by PhilippC** [comment]
maybe another small OS update?

**Comment by githubsean** [comment]
For what it's worth, I had the same issue after an update to Android 10 on my Pixel3 using the Offline version of the app.
The application would crash when enabling fingerprint unlock.
I tried clearing data. I tried re-installing. No luck.
I did work by first enabling for quick unlock, and then enabling for full unlock.
So while the issue is solved - there seems to be some underlying issue.
Cheers.

**Comment by aidankay1** [comment]
Same problem occurred a few days ago on my Pixel 2, Android 10. After leaving the settings alone since then, the issue seems to have fixed itself, though.

**Comment by BradleyDS2** [comment]
Started occurring for me a couple of weeks ago. Enabling for QuickUnlock does not fix the issue.

**Comment by PhilippC** [comment]
this should be fixed with 1.08. please re-open if not.

**Comment by mnilsson76** [comment]
I'm still getting this. Running 1.09a-pre1 currently but got the error also using the official 1.08.
Galaxy S9+ with Android 10, running rooted using Magisk 22.0.

[2021 16_58_37_140.txt](https://github.com/PhilippC/keepass2android/files/6263761/2021.16_58_37_140.txt)
