### ISSUE TITLE
URL not being passed to KP2A AutoFill plugin

### ISSUE THREAD

**Issue by Jon999999** [PhilippC/keepass2android#938]
Recently, KP2A AutoFill plugin for Android has not been receiving the correct URL for looking up the Keepass entry. This was previously working. It affects all four Android browsers I have tried (Firefox Focus, Firefox, Chrome, and Opera).

On the web browser itself, the pop-up bubble shows the correct URL (e.g., "KP2A AutoFillPlugin is requesting credentials for http://strava.com/login" or "Found multiple web domains: valid=www.strava.com, child=www.strava.com"). But when I click the KP2A AutoFill notification to open KP2A, it no longer automatically searches for the matching URL entry. Instead, the pop-up bubble shows a generic URL related to the browser that called it (e.g., "KP2A AutoFillPlugin is requesting credentials for androidapp://org.mozilla.focus" or "... for androidapp://com.android.chrome" or "... for androidapp://org.mozilla.firefox" or "... for androidapp://com.opera.browser").

It's as if the search parameter being passed by the KP2A AutoFill Plugin from the browser to KP2A is now the browser's URI instead of the URL of the current website.

As I wrote above, this used to work fine but broke sometime recently. The temporary workaround is to type the URL into the KP2A search field manually, but this is tedious, redundant, and prone to error.

Screenshots:

![focus_chrome](https://user-images.githubusercontent.com/31597590/64036547-6d529a00-cb21-11e9-908a-eedd514cba9d.png)

![ff_opera](https://user-images.githubusercontent.com/31597590/64036553-6fb4f400-cb21-11e9-8934-a541ea69c256.png)

Versions:

Android 8.1.0
KP2A Offline 1.06g
KP2A AutoFill Plugin 1.02
Firefox Focus 8.0.15
Chrome 76.0.3809.132
Firefox 68.0.2

**Comment by bartlibert** [comment]
Could this be related to the whitelisting mentioned [here](https://github.com/bitwarden/mobile/issues/477)?

**Comment by andreaippo** [comment]
Similar issue here, but with the Autofill framework, not the accessibility plugin, which I don't (want to) use. Except for the fact that with Autofill framework, Autofill somehow works on Firefox only. All other browsers I've tested show the Autofill popup with the hint to use keepass2android, but when I tap on it, the search is done by app package name, not by URL. I've mailed you about it, please let me know if there's anything I can do if you need more info on this.

Thanks a lot on advance.

**Comment by sba923** [comment]
Same here with Microsoft Edge. Globally, Keepass2Android hasn't been able to guess the entry and thus autofill in web forms for quite a while now. This used to work like a charm! ;-(

**Comment by cstegm** [comment]
I have the same issue i think these Issues should be linked here, because i think the are related.

https://github.com/PhilippC/keepass2android/issues/431
https://github.com/PhilippC/keepass2android/issues/1011

**Comment by leotzian** [comment]
Hi is there a solution to this, in Crome for Android autofill is working fine, I have the above problen in Opera for android

**Comment by PhilippC** [comment]
can you please test if this was fixed in the meantime, please install 1.08-pre2 for the test: https://play.google.com/apps/testing/keepass2android.keepass2android

@cstegm this issue is not about handling the URLs/package name for an entry, these issues are unrelated.

**Comment by Jon999999** [comment]
Good news! The problem appears to have been fixed in the meantime. Now when I click on “Fill with Keepass2Android” in a page’s login field in Firefox for Android, the proper Keepass entry is found and filled in.

 

Thank you!

**Comment by Jon999999** [comment]
Good news! The problem appears to have been fixed in the meantime. Now when I click on “Fill with Keepass2Android” in a page’s login field in Firefox for Android, the proper Keepass entry is found and filled in.

Thank you!

**Comment by fuzxi** [comment]
I am still having this issue on Keepass2Android v1.08b-pre2, with Bromite 81.0.4044.127.

**Comment by Najihel** [comment]
Hello,

Same issue on 1.08-r0. The app continue to search `com.opera.browser` instead of the URL in Opera

**Comment by sba923** [comment]
Running 1.08b-r0, it seems to work OK, including the "do you want to store...." prompt that was originally there but had disappeared at some point.

**Comment by bursterburster** [comment]
Fixed for my browser (Yuzu (webview)) with 1.08b-r0.
