### ISSUE TITLE
Cannot use Keepass2Android's keyboard for field entry

### ISSUE THREAD

**Issue by emicattt** [PhilippC/keepass2android#964]
I am not certain of the exact date I started having this issue, but I think I first noticed it on 18th September 2019. I have reinstalled Keepass2Android and Chrome, restarted my phone, made a new database with Keepass2Android, made a new database on my computer and tried Firefox and Microsoft Edge instead of Chrome. None of these fix the problem.

When I tap the padlock icon on the app's keyboard, I get a menu with the options "Select entry" and "Search for entry with com.android.chrome" (or equivalent for the other browsers). This is normal.

I tap "Select entry", select my database file, unlock the database and select an entry as normal.

I am returned to the app I want to enter the data into (eg Chrome).

I tap the padlock icon again, and get a menu with the options "Select another entry" and "Search for entry with com.android.chrome". I do not have any options to enter url, username, password etc.

If I tap "Select another entry" the problem reoccurs. If I tap "Search for entry with com.android.chrome", I am asked to unlock my database and then get "No search results".

I am using:
Version 1.07-r1 of Keepass2Android
Android 9
Model TA-1125 Nokia 3.1 Plus
Version 77.0.3865.92 of Chrome
Version 68.1.1 of Firefox
Version 42.0.4.3928 of Edge

If you need any more information, please tell me what you need.

**Comment by lee-tts** [comment]
Signed into Github to report this exact issue. After selecting an entry, either manually by opening the entry in the app, or by using the KP2A keyboard button, after selecting the desired entry, the entry is forgotten by the time you are back to the password field. 

Ie. I cannot choose the password I want to enter.

Hope there is a quick fix :)

**Comment by PhilippC** [comment]
does it also happen if you click the browser menu "Share URL" and select KP2A? (That's the recommended way of looking up credentials from Chrome)? (It's still a bug but might help to find it)

**Comment by lee-tts** [comment]
Yes, same result for me. I haven't had time to test extensively but it seems to be affected by TOTP. My TOTP settings were added via KeepassXC (Linux) and are in the form
`TOTP Seed`:`************************************`
`TOTP Settings`:`30;6`

**Comment by antonrunov** [comment]
I am experiencing the same issue with entries containing TOTP fields imported from KeePassXC. When I select these entries, there is no clipboard notification and no fields are available in KP2A keyboard. Entries without TOTP fields work fine. Please  let me now if any additional diagnostics might be helpful.

**Comment by antonrunov** [comment]
I just installed a beta version (1.07b-pre2) and the issue has gone. So I assume it's already fixed. Thanks, great job!

**Comment by fgianneschi** [comment]
> I am experiencing the same issue with entries containing TOTP fields imported from KeePassXC. When I select these entries, there is no clipboard notification and no fields are available in KP2A keyboard. Entries without TOTP fields work fine. Please let me now if any additional diagnostics might be helpful.

I'm experiencing the same issue on v.1.07-r1, which occurs only for TOTP fields created by KeePassXC (2.4.3).

**Comment by PhilippC** [comment]
Please switch to beta, should be fixed there. Please reopen if not.

**Comment by lee-tts** [comment]
Huge thanks @PhilippC ! Is the Beta available outside Google somewhere for us ungoogled users? Or will it be getting a release on github? Thanks again!

**Comment by gpion** [comment]
Sorry but unfortunatel not fixed for me still.
Currently using beta version 1.08-pre3 (Samsung Galaxy S9, Android 9.0)
Exact same issue.
Example of login form with this behavior:
https://www.darty.com/m/espace_client/connexion
